name: Build Windows EXE

on: workflow_dispatch

jobs:
  Build-Windows-EXE:
    runs-on: windows-latest
    steps:
      
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Cache Nuitka dependencies
        uses: actions/cache@v1
        with:
          path: C:\Users\runneradmin\AppData\Local\Nuitka
          key: ${{ runner.OS }}-nuitka-cache-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.OS }}-nuitka-cache-

      - name: Build EXE
        run: yes | python -m nuitka --standalone --onefile --output-dir="build" kasa_cli

